name: Pull Request Opened Workflow

on:
  pull_request:
    types: [opened]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GH_REPO: ${{ github.repository }}
  BACKLOG_PROJECT_KEY: ${{ secrets.BACKLOG_PROJECT_KEY }}
  BACKLOG_FQDN: ${{ secrets.BACKLOG_FQDN }}
  BACKLOG_API_KEY: ${{ secrets.BACKLOG_API_KEY }}

jobs:
  add_backlog_issue_url_to_pull_request:
    runs-on: ubuntu-latest
      
    steps:

    - name: Validate Backlog secrets.
      run: exit 1
      if: ${{ env.BACKLOG_PROJECT_KEY == '' || env.BACKLOG_FQDN == '' || env.BACKLOG_API_KEY == '' }}
        
    - name: Validate and get the source branch name.
      run: |
        echo "SOURCE_BRANCH=${{ github.head_ref }}" >> $GITHUB_ENV
        echo "IS_VALID_BRANCH_NAME=$([[ "$SOURCE_BRANCH" =~ "$BACKLOG_PROJECT_KEY"-[0-9]+ ]] ; echo $?)" >> $GITHUB_ENV
        
    - name: Get issue key.
      run: echo "ISSUE_KEY=${[[ "$SOURCE_BRANCH" =~ ("$BACKLOG_PROJECT_KEY"-[0-9]+) ]] ; echo BASH_REMATCH[1]}" >> $GITHUB_ENV
      if: ${{ env.IS_VALID_BRANCH_NAME }}

    - name: Get the current PR body
      run: echo "PULL_REQUEST_BODY=$(gh pr view ${{ github.event.number }} --json body -q ".body")" >> $GITHUB_ENV
      if: ${{ env.IS_VALID_BRANCH_NAME }}
        
    - name: Add a issue URL to the pull request's body
      run: |
        NEW_LINE="https://${BACKLOG_FQDN}/view/${ISSUE_KEY}"
        NEW_BODY="${NEW_LINE}\n\n${PULL_REQUEST_BODY}"
        echo -e "$NEW_BODY" > msg # Write a file temporally.
        export msg=$(cat msg) ; gh pr edit ${{ github.event.number }} --body "$msg"
      if: ${{ env.IS_VALID_BRANCH_NAME }}