name: Pull Request Opened Workflow (test)

on:
  pull_request:
    types: [opened]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GH_REPO: ${{ github.repository }}
  BACKLOG_PROJECT_KEY: ${{ secrets.BACKLOG_PROJECT_KEY }}
  BACKLOG_FQDN: ${{ secrets.BACKLOG_FQDN }}

jobs:
  handle_opened_pull_request:
    runs-on: ubuntu-latest

    steps:
        
    - name: Set Backlog issue URL.
      uses: RikiyaOta/link-github-backlog-action@main
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        github-repo: ${{ github.repository }}
        backlog-project-key: ${{ secrets.BACKLOG_PROJECT_KEY }}
        backlog-fqdn: ${{ secrets.BACKLOG_FQDN }}