name: Pull Request Opened Workflow

on:
  pull_request:
    types: [opened]

jobs:
  handle_opened_pull_request:
    runs-on: ubuntu-latest
      
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GH_REPO: ${{ github.repository }}
      BACKLOG_PROJECT_KEY: ${{ secrets.BACKLOG_PROJECT_KEY }}
      BACKLOG_FQDN: ${{ secrets.BACKLOG_FQDN }}
      BACKLOG_API_KEY: ${{ secrets.BACKLOG_API_KEY }}
      
    steps:

    - name: Check secrets about Backlog exist or not.
      run: exit 1
      if: ${{ env.BACKLOG_PROJECT_KEY == '' || env.BACKLOG_FQDN == '' || env.BACKLOG_API_KEY == '' }}
    
    - name: Get the source branch name.
      run: echo "SOURCE_BRANCH=${{ github.head_ref }}" >> $GITHUB_ENV
      if: success()

    - name: Validate the source branch name's pattern and get the issue key.
      run: |
        if [[ "$SOURCE_BRANCH" =~ (${{ env.BACKLOG_PROJECT_KEY }}-[0-9]+) ]]; then
          echo "ISSUE_KEY=${BASH_REMATCH[1]}" >> $GITHUB_ENV
        fi
      if: success()

    - name: Get the current PR body
      run: |
        PULL_REQUEST_BODY=$(gh pr view ${{ github.event.number }} --json body -q ".body")
        echo "PULL_REQUEST_BODY=${PULL_REQUEST_BODY}" >> $GITHUB_ENV
      if: success()
        
    - name: Check the Pull Request Body
      run: echo "$PULL_REQUEST_BODY"
      if: success()
        
    - name: Add a issue URL to the pull request's body
      run: |
        NEW_LINE="# Backlog Issue\n\nhttps://${BACKLOG_FQDN}/view/${ISSUE_KEY}"
        NEW_BODY="${NEW_LINE}\n\n${PULL_REQUEST_BODY}"
        echo -e "$NEW_BODY" > msg # Write a file temporally.
        export msg=$(cat msg) ; gh pr edit ${{ github.event.number }} --body "$msg"